name: Linux
on: [push, pull_request]

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-18.04
    container: swift:latest
    steps:
      - uses: actions/checkout@v1
      - run: swift test --enable-test-discovery
