name: macOS
on: [push, pull_request]

jobs:
  macos:
    name: macOS
    # I'd like to specify macOS-10.15 explicitly, but GitHub only
    # supports macOS-latest.
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - run: swift test
